 user:
   username: HelloWorld
   age: 20
   sex: true
   born: 2019/08/18
   parent: {father: Tomcat , mother: Spring}
   idCards:
     - S001
     - S002
     - S003
   address:
     name: 河南省林州市
     door: A461
   address-list:
       - name: address1
       - door: door1
       - name: address2
       - door: door2
       - name: address3
       - door: door3
